apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: acme
spec:
  acme:
    # Remember to update this if you use this manifest to obtain real certificates :)
    email: mjurisic86@gmail.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # To use the production environment, use the following line instead:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: ngnix