apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: acme
spec:
  selector:
    app: demo-pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: no-https
    # - protocol: TCP
    #   port: 443
    #   targetPort: 8443
    #   name: https